### ISSUE TITLE
Theming Changes

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/TemplateDocs#1]
We want to implement *some* of the design concepts that @joewheaton has created for the [Weebly Riverscapes](https://riverscapes.weebly.com) site. Let's break this into phases.

## Phase 1 Changes

We will take the following design elements from [this page](https://riverscapes.weebly.com/who-we-are.html) and implement them for all TemplateDocs pages:

* Header image (i.e. the hillshade image)
* Page title font (i.e. "WHO IS THE")
* Header fonts (e.g. "LIKE MINDED...")
* Regular text font (e.g. "Some of us are....")
* Hyperlink color (the rusty brown one)
* Riverscapes icon top left that links back to main riverscapes.com site
* Keep existing TemplateDocs **optional** header menu but style it like the weebly site.

## Other Comments

* Keep the TemplateDocs side bar boxes for page and site contents
* Note that the "one page love" scrolling home page is out of scope for phase 1.

**Comment by joewheaton** [comment]
All sounds good. Let's have the default background be white or that lighter hillshade background I made that black text contrasts well on. We don't need the 'one page love' scrolling fluff home page. Just stick with what we have in Git-hosted sites and if we need fluff we use Weebly.

**Comment by joewheaton** [comment]
@MattReimer we will need a way to add the tool logo and tool banner somewhere in the header... shout when you get to this and you can give me parameters on how we need to do this.

**Comment by MattReimer** [comment]
@joewheaton see 73b803c for how to inject logos into the page

**Comment by MattReimer** [comment]
I'm calling this done for now. Let's either re-open or file a separate issue if there are more enhancements needed.
