### ISSUE TITLE
Question about Buttons...

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/TemplateDocs#10]
@MattReimer, thanks for the helpful template for how to [incorporate buttons](https://riverscapes.github.io/TemplateDocs/styleguide.html#buttons). I have a silly, low-priority question about how to use those  [font-awesome icon sets](https://fontawesome.com) for icons. I want to do what you suggest and use one of those icons, but I'm having trouble and wondering if it is because I'm referencing classes we just don't ship with? You suggest a syntax like:
```
<a class="button" href="#"><i class="fa fa-home"></i> 'home' icon </a>
```
The key is that `<i class="fa fa-home"></i>` tag. I browsed around on FontAwesome and found [an icon I wanted to use for a zip archive](https://fontawesome.com/icons/file-archive?style=solid). On that [page](https://fontawesome.com/icons/file-archive?style=solid), they suggest using `<i class="fas fa-file-archive"></i>`. I tried that out:

```
<a class="button" href="#"><i class="fas fa-file-archive"></i> Exercise Data </a><br>
```
I can create the button, but it doesn't seem to find that class. Any suggestions?  No rush..

**Comment by joewheaton** [comment]
I'm thinking you're going to tell me I need to add references to those specific images here: https://github.com/Riverscapes/TemplateDocs/blob/master/assets/css/app.css

**Comment by MattReimer** [comment]
Sorry @joewheaton .... so much stuff I take for granted. 

The problem with font-awesome (and it's a small list) is that they're constantly adding new ones and the library I ship doesn't contain them

We presently ship with Font-Awesome 4.7.0

You can see the full list for this version here:

<https://fontawesome.com/v4.7.0/>

Thank goodness they keep old versions of their site online. 

May I suggest `<i class="fa fa-file-archive-o "></i>` as a replacement?

**Comment by joewheaton** [comment]
Thanks Matt!

_____________________
Dr. Joseph M. Wheaton
435-554-1247 (direct) | http://www.joewheaton.org
