### ISSUE TITLE
Top Navigation Menu

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/TemplateDocs#4]
In contrast to the auto-populating sidebar menu, which I like, can we please add a static top menu (using same #3 Fonts as sidebar) in the upper right hand corner of page to look like:
![top menu](https://user-images.githubusercontent.com/9723905/37693016-5c2a58a6-2c82-11e8-8ab0-2003b6ba2184.png).

Unlike the menu on the [riverscapes.xyz]{http://riverscapes.weebly.com} weebly hosted site, that will change all the time, I'm thinking this menu is fixed and static and is just meant for funneling traffic back to the main Riverscapes Consortium page.

Specifically, the menus across the top should be (with nested sub-menus only for those shown below) and static hyperlinks (note these are now have base urls of riverscapes.weebly.com, but will soon be as listed below):
- [Home](http://riverscapes.xyz)
  - [About](http://riverscapes.xyz/about.html)
  - [Who We Are](http://riverscapes.xyz/who-we-are.html)
  - [News](http://riverscapes.xyz/news.html)
- [RC Tools](http://riverscapes.xyz/rc-tools.html)
- [RC Science](http://riverscapes.xyz/rc-science.html)
- [RC Data](http://riverscapes.xyz/rc-data.html)
- [RC Help](http://riverscapes.xyz/rc-help.html)

The drop down on home should do something like:
![dropdown](https://user-images.githubusercontent.com/9723905/37693160-7f93b5de-2c83-11e8-89f2-93cbc47ec13c.png)

**Comment by philipbaileynar** [comment]
@joewheaton  see the _config.yml file in the root of each site. You can configure the top menu there.

**Comment by joewheaton** [comment]
Okay, I tried to fix this, but I broke it somehow and got a few page build errors. (see commit above).  So @philipbaileynar  or @MattReimer can you please:
1. Help with whatever I did to break the menu,
2. Also implement the requested visual changes...

**Comment by MattReimer** [comment]
@joewheaton The problem was a single space. YAML is indentations specific. This has been fixed

**Comment by joewheaton** [comment]
Nice one. Thanks!
