### ISSUE TITLE
Header Requests

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/TemplateDocs#5]
In addition to our request for a top navigation menu (#4), we need:
1.  A mechanism to have a standard header image (you give us constraints), which we can substitute out as site header specific to that model. The current functionality is great in which clicking on that takes us back to the `{ base.url}/index.html` home page for that site. For example BRAT 
![brat_banner_web](https://user-images.githubusercontent.com/9723905/37693237-ea9e1180-2c83-11e8-8b41-73018e5a1584.png)
2. A static 40 x 40 Riverscapes Consortium button (similar to that on main [Riverscapes Site](http://riverscapes.xyz) in upper left corner that links us back to main riverscapes.xyz page.  ![riverscapesconsortium_logo_white_bhs_icononly](https://user-images.githubusercontent.com/9723905/37693410-22ec2f94-2c85-11e8-85c5-0a4a81234314.png)
3.  Should display using the Oswald font @ `font-size: 80px;` for Page Titles (if specified in header of md file). Much like you already did [here](http://rcat.riverscapes.xyz/CRBR-CATMapAtlas.html)

**Comment by joewheaton** [comment]
I noticed that request number 2 above is present and implemented in this TemplatesDocs, but for whatever reason is not showing up in the theme changes @philipbaileynar implemented in  [BRAT](http://brat.riverscapes.xyz) or [RCAT](http://rcat.riverscapes.xyz) or [GCD](http://gcd.riverscapes.xyz)? Thoughts? It would be good for @lhaycock  and I to know how to do this...

**Comment by MattReimer** [comment]
@joewheaton the icon was tied to the presence of the custom menu. that has been decoupled so you should see the icon even when there is no menu

**Comment by MattReimer** [comment]
I've hardcoded  http://riverscapes.xyz to the button
