### ISSUE TITLE
Custom Site Icons or favicons

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/TemplateDocs#6]
I'm pretty sure you told us how to do this, but neither @lhaycock or I could remember how to customize the site icon. Can you point us to the help that described this? I think there is also a page that you made somewhere that had more tips on how to do all this stuff on northarrowresearch.com.

Can we please make the default favicon for these projects the Riverscapes Consortium logo:
![favicon-16x16](https://user-images.githubusercontent.com/9723905/37693545-09444698-2c86-11e8-9c1c-a1ff6b49d36d.png)

Then Landon and I just need to know how to customize them where we have our own for specific tools.

Here it is:
[RiverscapesIcon.zip](https://github.com/Riverscapes/TemplateDocs/files/1831988/RiverscapesIcon.zip)

**Comment by philipbaileynar** [comment]
http://riverscapes.northarrowresearch.com/Technical_Reference/applying_theme.html#updating-your-favicon

**Comment by joewheaton** [comment]
Thanks @philipbaileynar. I've updated the [ReadMe file](https://github.com/Riverscapes/TemplateDocs/blob/master/README.md)  with this[ commit](https://github.com/Riverscapes/TemplateDocs/commit/1a8107942af94ed97680f6c4cbecf1ab651e9339), so that we can find the stuff easier!
