### ISSUE TITLE
Sidebar Visual

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/TemplateDocs#7]
Hey @MattReimer. I like how the behavior of the sidebar shows Black for the current menu we're on, and orange for the rest of things.  However, can you set a background image for Site Contents and PAge Contents menus instead of just a background color? Specifically, I'm thinking the grey-scale hillshade (clipped or scaled down to appropriate size of course and maybe even brighter/lighter) would be good:
![buffalofork_rs_hs](https://user-images.githubusercontent.com/9723905/37694370-41bda068-2c8c-11e8-9854-94194d5d8068.png)

**Comment by MattReimer** [comment]
I'm going to suggest we don't do this. I tried it and there's no amount of lightness or blurriness that doesn't distract from the text in the menu.

**Comment by joewheaton** [comment]
Good stuff. Thanks for checking it out and implementing all the other requests! Much obliged!
